name: rsmpi Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
defaults:
  run:
    shell: bash
jobs:
  test:
    name: Test rsmpi
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - windows-2022
          - ubuntu-latest
          - macos-latest
        rust:
          - 1.36.0 # First version with MaybeUninit
          - stable
          - nightly
    steps:
      - name: Install LLVM (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-10-dev
      - name: Install LLVM (Mac)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install llvm@13
          env
      - name: Install LLVM (Windows)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          choco install llvm --version 13.0.0 -y
          env
      - name: Clang Version
        run: clang --version
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
