name: rsmpi Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
defaults:
  run:
    shell: bash
jobs:
  test:
    name: Test rsmpi
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable
          - nightly
        mpi_package:
          - libmpich-dev
        include:
          - os: ubuntu-latest
            rust: 1.36.0 # First version with MaybeUninit
            mpi_package: libmpich-dev
          - os: macos-latest
            rust: stable
            mpi_package: open-mpi
          - os: ubuntu-latest
            rust: stable
            mpi_package: libopenmpi-dev
    steps:
      - name: Install (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-dev libclang-dev pkgconf ${{ matrix.mpi_package }}
      - name: Install (Mac)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install llvm@13 ${{ matrix.mpi_package }}
          env
      - name: Install (Windows)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          choco install llvm --version 13.0.0 -y
          env
      - name: Clang Version
        run: clang --version
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
      - name: Cargo Test all-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
